class City < ActiveHash::Base
  self.data = [
    { id: 0, data: '---' },
    { id: 1, data: '北九州市門司区' },
    { id: 2, data: '北九州市若松区' },
    { id: 3, data: '中華料理' },
    { id: 4, data: 'アジア・エスニック' },
    { id: 5, data: '焼肉' },
    { id: 6, data: '鍋' },
    { id: 7, data: 'ラーメン' },
    { id: 8, data: 'パン・サンドイッチ' },
    { id: 9, data: 'カフェ' },
    { id: 10, data: 'スイーツ' },
    { id: 11, data: '---' },
    { id: 12, data: '北九州市門司区' },
    { id: 13, data: '洋食・西洋料理' },
    { id: 14, data: '中華料理' },
    { id: 15, data: 'アジア・エスニック' },
    { id: 16, data: '焼肉' },
    { id: 17, data: '鍋' },
    { id: 18, data: 'ラーメン' },
    { id: 19, data: 'パン・サンドイッチ' },
    { id: 20, data: 'カフェ' },
    { id: 21, data: 'スイーツ' },
    { id: 22, data: '---' },
    { id: 23, data: '北九州市門司区' },
    { id: 24, data: '洋食・西洋料理' },
    { id: 25, data: '中華料理' },
    { id: 26, data: 'アジア・エスニック' },
    { id: 27, data: '焼肉' },
    { id: 28, data: '鍋' },
    { id: 29, data: 'ラーメン' },
    { id: 30, data: 'パン・サンドイッチ' },
    { id: 31, data: 'カフェ' },
    { id: 32, data: 'スイーツ' }
  ]
end
